### ISSUE TITLE
Using composes with psuedo-selectors

### ISSUE THREAD

**Issue by ryngonzalez** [css-modules/css-modules-loader-core#29]
Is there anyway to use composes with a psuedo-selector? For instance, like this:

``` css
.item:last-child {
  composes: no-border from 'shared/styles.css';
}
```

**Comment by geelen** [comment]
No, that's not possible. See https://github.com/css-modules/css-modules/issues/33#issuecomment-133623241 for a bit more discussion, but the short answer is that CSS Modules adds extra classes to an element, but not dynamically, so there's no way for it to only add that extra class to the last `.item` in a list, or anything. You can `compose` something that _has_ pseudo-selectors though:

``` css
/* shared/styles.css */

.normal-border {
  border: 1px solid;
}

.no-border-on-last:last-child {
  border: none;
}
```

``` css
.item {
  composes: normal-border no-border-on-last from 'shared/styles.css';
}
```

This feels weird coming from Sass, I'll admit, but lets you break up the behaviour in whichever way makes sense. In fact, in `shared/styles.css` you could also add do something like this:

``` css
.normal-border {
  border: 1px solid;
}

.list-borders {
  composes: normal-border;
}
.list-borders:last-child {
  border: none;
}
```

Then you've wrapped up something complex (borders on all but last) into a single name `list-borders` that you can reuse.

Does that answer your question? Please close the issue if so, otherwise I'm happy to explain further.
